/**
 * AI Image Generation Service (Nano Banana Pro Engine)
 * This service handles communication with image generation APIs.
 */

export const generatePopImage = async (params: {
    title: string;
    theme: string;
    copy: string;
    orientation: 'portrait' | 'landscape';
}): Promise<string> => {
    // APIキーの確認 (Nano Banana Pro の要件)
    const apiKey = localStorage.getItem('nano_banana_api_key') || (import.meta as any).env?.VITE_GEMINI_API_KEY;

    if (!apiKey) {
        throw new Error('API_KEY_MISSING');
    }

    // URLエンコーディングエラー（日本語が弾かれる問題）を防ぐため、英語カテゴリに変換
    const englishKeywords: Record<string, string> = {
        'キャベツ': 'fresh green cabbage',
        'トマト': 'fresh red tomatoes',
        'りんご': 'fresh red apples',
        'みかん': 'mandarin oranges',
        'いちご': 'fresh strawberries',
        'テスト': 'assortment of fresh vegetables'
    };

    // 辞書にない場合は安全な汎用表現を使用
    const safeEnglishTitle = englishKeywords[params.title] || 'fresh produce and fruits';

    // URLエンコーディングの最適化（長すぎるとエラーになる場合があるため調整）
    const cleanPrompt = `Professional retail POP advertisement photography, ${safeEnglishTitle}, high quality food, ${params.orientation === 'landscape' ? "landscape wide shot" : "portrait vertical shot"}`;

    // --- Gemini Imagen 3 API Integration ---
    // Pollinationsがダウンしているため、本物の生成AI(Gemini Imagen)を利用します。
    const aspectRatio = params.orientation === 'landscape' ? "16:9" : "3:4";

    try {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                instances: [
                    { prompt: cleanPrompt }
                ],
                parameters: {
                    sampleCount: 1,
                    aspectRatio: aspectRatio
                }
            })
        });

        if (!response.ok) {
            const errorData = await response.json();
            console.error("Gemini API Error:", errorData);
            throw new Error(`Gemini API Error: ${response.status}`);
        }

        const data = await response.json();

        if (data.predictions && data.predictions.length > 0) {
            const base64Image = data.predictions[0].bytesBase64Encoded;
            return `data:image/jpeg;base64,${base64Image}`;
        } else {
            throw new Error("No image generated by Gemini API");
        }
    } catch (error: any) {
        console.error("Failed to generate image via Gemini:", error);

        // API Keyが無効な場合は特別なエラーを投げてUIに拾わせる
        if (error.message && error.message.includes('400')) {
            throw new Error('API_KEY_INVALID');
        }

        // フォールバック用のフラグメントを含める（App.tsxでフォールバックURLを生成するため）
        const width = params.orientation === 'landscape' ? 1200 : 800;
        const height = params.orientation === 'landscape' ? 800 : 1200;
        return `#fallback=${width}x${height}?${encodeURIComponent(params.title)}`;
    }
};
